import PDFDocument from "pdfkit";

import {
  getContractReportData,
} from "../services/reportService.js";

const addTitle = (doc, title) => {
  doc
    .fontSize(20)
    .font("Helvetica-Bold")
    .text(title, {
      align: "center",
    });

  doc.moveDown();
};

const addSection = (doc, title) => {
  doc.moveDown(0.8);

  doc
    .fontSize(14)
    .font("Helvetica-Bold")
    .text(title);

  doc.moveDown(0.3);
};

const addLabelValue = (
  doc,
  label,
  value
) => {
  doc
    .fontSize(10)
    .font("Helvetica-Bold")
    .text(`${label}: `, {
      continued: true,
    })
    .font("Helvetica")
    .text(String(value ?? "Not specified"));

  doc.moveDown(0.2);
};

const addBulletList = (
  doc,
  items,
  formatter
) => {
  if (!items || items.length === 0) {
    doc
      .fontSize(10)
      .font("Helvetica")
      .text("No information available.");

    return;
  }

  items.forEach((item) => {
    const text = formatter
      ? formatter(item)
      : typeof item === "string"
        ? item
        : JSON.stringify(item);

    doc
      .fontSize(10)
      .font("Helvetica")
      .text(`• ${text}`, {
        indent: 12,
      });

    doc.moveDown(0.15);
  });
};

const addFooter = (doc) => {
  const range = doc.bufferedPageRange();

  for (
    let i = range.start;
    i < range.start + range.count;
    i++
  ) {
    doc.switchToPage(i);

    doc
      .fontSize(8)
      .font("Helvetica")
      .text(
        `AI Contract Review Assistant | Page ${i + 1}`,
        50,
        750,
        {
          align: "center",
          width: 500,
        }
      );
  }
};

export const generateContractReport =
  async (req, res) => {
    try {
      const report =
        await getContractReportData(
          req.params.id,
          req.user.id
        );

      const safeFileName =
        (report.contract.title || "contract")
          .replace(/[^a-z0-9]/gi, "_")
          .replace(/_+/g, "_");

      const fileName =
        `${safeFileName}_report.pdf`;

      res.setHeader(
        "Content-Type",
        "application/pdf"
      );

      res.setHeader(
        "Content-Disposition",
        `attachment; filename="${fileName}"`
      );

      const doc = new PDFDocument({
        size: "A4",
        margin: 50,
        bufferPages: true,
      });

      doc.pipe(res);

      // ------------------------------------------------
      // TITLE
      // ------------------------------------------------

      addTitle(
        doc,
        "AI CONTRACT REVIEW REPORT"
      );

      doc
        .fontSize(11)
        .font("Helvetica")
        .text(
          "Generated by AI Contract Review Assistant",
          {
            align: "center",
          }
        );

      doc.moveDown(1.5);

      // ------------------------------------------------
      // CONTRACT INFORMATION
      // ------------------------------------------------

      addSection(
        doc,
        "1. Contract Information"
      );

      addLabelValue(
        doc,
        "Contract Title",
        report.contract.title
      );

      addLabelValue(
        doc,
        "Contract Type",
        report.contract.contractType
      );

      addLabelValue(
        doc,
        "File Name",
        report.contract.fileName
      );

      addLabelValue(
        doc,
        "Version",
        report.contract.versionNumber
      );

      addLabelValue(
        doc,
        "Uploaded At",
        new Date(
          report.contract.uploadedAt
        ).toLocaleString("en-IN")
      );

      // ------------------------------------------------
      // OVERVIEW
      // ------------------------------------------------

      addSection(
        doc,
        "2. Contract Overview"
      );

      addLabelValue(
        doc,
        "Document Type",
        report.overview.documentType
      );

      addLabelValue(
        doc,
        "AI Confidence",
        report.overview.confidence !== null
          ? `${report.overview.confidence}%`
          : "Not specified"
      );

      addLabelValue(
        doc,
        "Parties",
        report.overview.partiesInvolved
      );

      addLabelValue(
        doc,
        "Effective Date",
        report.overview.effectiveDate
      );

      addLabelValue(
        doc,
        "Expiration Date",
        report.overview.expirationDate
      );

      addLabelValue(
        doc,
        "Governing Law",
        report.overview.governingLaw
      );

      addLabelValue(
        doc,
        "Jurisdiction",
        report.overview.jurisdiction
      );

      addLabelValue(
        doc,
        "Contract Health",
        report.overview.contractHealth
      );

      // ------------------------------------------------
      // EXECUTIVE SUMMARY
      // ------------------------------------------------

      addSection(
        doc,
        "3. Executive Summary"
      );

      doc
        .fontSize(10)
        .font("Helvetica")
        .text(report.summary, {
          align: "left",
          lineGap: 3,
        });

      // ------------------------------------------------
      // RISK ANALYSIS
      // ------------------------------------------------

      addSection(
        doc,
        "4. Risk Analysis"
      );

      addLabelValue(
        doc,
        "Risk Score",
        report.risk.score
      );

      addLabelValue(
        doc,
        "Risk Level",
        report.risk.level
      );

      const statistics =
        report.risk.statistics;

      addLabelValue(
        doc,
        "Low Risks",
        statistics.lowRisks ?? 0
      );

      addLabelValue(
        doc,
        "Medium Risks",
        statistics.mediumRisks ?? 0
      );

      addLabelValue(
        doc,
        "High Risks",
        statistics.highRisks ?? 0
      );

      addLabelValue(
        doc,
        "Critical Clauses",
        statistics.criticalClauses ?? 0
      );

      // ------------------------------------------------
      // IMPORTANT TERMS
      // ------------------------------------------------

      addSection(
        doc,
        "5. Important Contract Terms"
      );

      addLabelValue(
        doc,
        "Payment Terms",
        report.importantTerms.paymentTerms
      );

      addLabelValue(
        doc,
        "Termination",
        report.importantTerms.terminationClause
      );

      addLabelValue(
        doc,
        "Confidentiality",
        report.importantTerms.confidentiality
      );

      addLabelValue(
        doc,
        "Renewal",
        report.importantTerms.renewal
      );

      // ------------------------------------------------
      // IMPORTANT DATES
      // ------------------------------------------------

      addSection(
        doc,
        "6. Important Dates & Timeline"
      );

      addBulletList(
        doc,
        report.timeline,
        (item) => {
          if (typeof item === "string") {
            return item;
          }

          const title =
            item.title ||
            item.event ||
            item.name ||
            "Event";

          const date =
            item.date ||
            item.value ||
            "";

          const description =
            item.description ||
            "";

          return `${title}${
            date ? ` — ${date}` : ""
          }${
            description
              ? `: ${description}`
              : ""
          }`;
        }
      );

      // ------------------------------------------------
      // OBLIGATIONS
      // ------------------------------------------------

      addSection(
        doc,
        "7. Contract Obligations"
      );

      addBulletList(
        doc,
        report.obligations,
        (item) => {
          if (typeof item === "string") {
            return item;
          }

          const title =
            item.title ||
            item.name ||
            item.obligation ||
            "Obligation";

          const description =
            item.description ||
            "";

          const deadline =
            item.deadline ||
            item.dueDate ||
            "";

          return `${title}${
            description
              ? `: ${description}`
              : ""
          }${
            deadline
              ? ` | Deadline: ${deadline}`
              : ""
          }`;
        }
      );

      // ------------------------------------------------
      // CLAUSES & RISKS
      // ------------------------------------------------

      addSection(
        doc,
        "8. Key Clauses & Risk Details"
      );

      addBulletList(
        doc,
        report.risk.clauses,
        (item) => {
          if (typeof item === "string") {
            return item;
          }

          const name =
            item.name ||
            item.title ||
            item.clause ||
            "Clause";

          const risk =
            item.riskLevel ||
            item.risk ||
            "";

          const description =
            item.description ||
            item.explanation ||
            "";

          return `${name}${
            risk
              ? ` [${risk}]`
              : ""
          }${
            description
              ? `: ${description}`
              : ""
          }`;
        }
      );

      // ------------------------------------------------
      // RECOMMENDATIONS
      // ------------------------------------------------

      if (
        report.recommendations &&
        report.recommendations.length > 0
      ) {
        addSection(
          doc,
          "9. Review Recommendations"
        );

        addBulletList(
          doc,
          report.recommendations,
          (item) => {
            if (typeof item === "string") {
              return item;
            }

            return (
              item.description ||
              item.text ||
              item.recommendation ||
              JSON.stringify(item)
            );
          }
        );
      }

      // ------------------------------------------------
      // DISCLAIMER
      // ------------------------------------------------

      addSection(
        doc,
        "Report Notice"
      );

      doc
        .fontSize(9)
        .font("Helvetica")
        .text(
          "This report is generated from automated AI-based contract analysis. It is intended to assist with document understanding and does not constitute legal advice. Important contractual decisions should be reviewed by an appropriately qualified legal professional."
        );

      doc.moveDown();

      doc
        .fontSize(8)
        .text(
          `Report generated on ${report.generatedAt.toLocaleString(
            "en-IN"
          )}.`
        );

      addFooter(doc);

      doc.end();
    } catch (error) {
      console.error(
        "Generate contract report error:",
        error
      );

      if (!res.headersSent) {
        return res
          .status(error.statusCode || 500)
          .json({
            error:
              error.code || "server_error",
            message:
              error.statusCode &&
              error.statusCode < 500
                ? error.message
                : "Failed to generate contract report.",
          });
      }

      res.end();
    }
  };